services:
  - type: web
    name: acopio-api
    env: python
    buildCommand: "pip install uv && uv sync --frozen --system && alembic upgrade head"
    startCommand: "fastapi run app/main.py --port $PORT"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_SECRET
        sync: false
