"""add_dlq_and_extend_sync_log

Revision ID: 898ba293865e
Revises: 0001_initial
Create Date: 2026-06-30 21:00:40.250041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898ba293865e'
down_revision: Union[str, Sequence[str], None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_letter_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('event_payload', sa.String(), nullable=False),
    sa.Column('error_reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sync_id'], ['sync_log.sync_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_queue_id'), 'dead_letter_queue', ['id'], unique=False)
    op.add_column('sync_log', sa.Column('centro_acopio_id', sa.String(length=50), nullable=True))
    op.add_column('sync_log', sa.Column('total_events', sa.Integer(), nullable=True))
    op.add_column('sync_log', sa.Column('processed_count', sa.Integer(), nullable=True))
    op.add_column('sync_log', sa.Column('failed_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_log', 'failed_count')
    op.drop_column('sync_log', 'processed_count')
    op.drop_column('sync_log', 'total_events')
    op.drop_column('sync_log', 'centro_acopio_id')
    op.drop_index(op.f('ix_dead_letter_queue_id'), table_name='dead_letter_queue')
    op.drop_table('dead_letter_queue')
    # ### end Alembic commands ###
